name: Auto Tag

on:
  pull_request_target:
    types: [opened, synchronize]
  push:
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get current tag
      id: current-tag
      run: |
        git fetch --tags
        TAG=$(git tag --sort=-v:refname | head -n 1)
        echo "tag=$TAG" >> $GITHUB_ENV

    - name: Increment version
      id: increment
      run: |
        if [ -z "${{ env.tag }}" ]; then
          NEW_TAG="v0.0.1"
        else
          TAG=${{ env.tag }}
          echo "Current tag: $TAG"
          IFS='.' read -r -a VERSION_PARTS <<< "${TAG#v}"
          VERSION_PARTS[2]=$((VERSION_PARTS[2] + 1
