name: Auto Tag

on:
  pull_request_target:
    types: [opened, synchronize]
  push:
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest

    env:
      ACTIONS_PAT: ${{ secrets.ACTIONS_PAT }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get current tag
      id: current-tag
      run: |
        git fetch --tags
        TAG=$(git tag --sort=-v:refname | head -n 1)
        echo "tag=$TAG" >> $GITHUB_ENV

    - name: Increment version
      id: increment
      run: |
        if [ -z "${{ env.tag }}" ]; then
          NEW_TAG="v0.0.1"
        else
          TAG=${{ env.tag }}
          echo "Current tag: $TAG"
          IFS='.' read -r -a VERSION_PARTS <<< "${TAG#v}"
          VERSION_PARTS[2]=$((VERSION_PARTS[2] + 1))
          NEW_TAG="v${VERSION_PARTS[0]}.${VERSION_PARTS[1]}.${VERSION_PARTS[2]}"
        fi
        echo "new_tag=$NEW_TAG" >> $GITHUB_ENV

    - name: Print PAT for debugging
      run: |
        echo "ACTIONS_PAT starts with: ${ACTIONS_PAT:0:4}"

    - name: Create new tag and latest tag
      run: |
        NEW_TAG=${{ env.new_tag }}
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git tag $NEW_TAG
        git tag -f latest
        git push https://${{ secrets.ACTIONS_PAT }}@github.com/${{ github.repository }} --tags
