name: Conditional Auto Tag

on:
  push:
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.ACTIONS_PAT }}

    - name: Get commit message
      id: get-commit-message
      run: |
        COMMIT_MESSAGE=$(git log -1 --pretty=%B)
        echo "commit_message=$COMMIT_MESSAGE" >> $GITHUB_ENV

    - name: Check for tag keyword in commit message
      id: check-tag-keyword
      run: |
        if echo "${{ env.commit_message }}" | grep -iq "#tag"; then
          echo "contains_tag_keyword=true" >> $GITHUB_ENV
        else
          echo "contains_tag_keyword=false" >> $GITHUB_ENV
        fi

    - name: Get current tag
      id: current-tag
      if: env.contains_tag_keyword == 'true'
      run: |
        git fetch --tags
        TAG=$(git tag --sort=-v:refname | head -n 1)
        echo "tag=$TAG" >> $GITHUB_ENV

    - name: Increment version
      id: increment
      if: env.contains_tag_keyword == 'true'
      run: |
        if [ -z "${{ env.tag }}" ]; then
          NEW_TAG="v0.0.1"
        else
          TAG=${{ env.tag }}
          echo "Current tag: $TAG"
          IFS='.' read -r -a VERSION_PARTS <<< "${TAG#v}"
          VERSION_PARTS[2]=$((VERSION_PARTS[2] + 1))
          NEW_TAG="v${VERSION_PARTS[0]}.${VERSION_PARTS[1]}.${VERSION_PARTS[2]}"
        fi
        echo "new_tag=$NEW_TAG" >> $GITHUB_ENV

    - name: Create new tag and latest tag
      if: env.contains_tag_keyword == 'true'
      env:
        ACTIONS_PAT: ${{ secrets.ACTIONS_PAT }}
      run: |
        NEW_TAG=${{ env.new_tag }}
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git tag $NEW_TAG
        git tag -f latest
        git push https://${{ secrets.ACTIONS_PAT }}@github.com/${{ github.repository }} $NEW_TAG
        git push https://${{ secrets.ACTIONS_PAT }}@github.com/${{ github.repository }} -f latest
